/** Runtime helpers embedded in each generated `styled-system`. */
export { createMergeCss } from './classname'
export { cloneStyles } from './clone-styles'
export { compact } from './compact'
export { toHash } from './hash'
export { memo } from './memo'
export { getRecipeIdentity } from './recipe-identity'
export { mergeProps } from './merge-props'
export { createPatternFns, getPatternStyles } from './pattern-fns'
export { getSlotCompoundVariant, getSlotRecipes } from './slot'
export { splitProps } from './split-props'
export { uniq } from './uniq'
